
development:
  adapter: postgresql
  database: cookbook_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cookbook_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cookbook_prod
  pool: 5
  timeout: 5000

